# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63ffef186466d31d4f13f81dc79ce8ff89b94c55a3bfd1ccb44df3f91e777cb70e8369c4b7557e9c331cc174c69a0b3594b6a5a282a26fb4894460c94ae803ef

test:
  secret_key_base: ed62e3347ccc33868ac615c2a2b1bf0643195dd1b00af4f9cecdbf2939342212bbf9e9887af98953b2a3c09060ebdc44878daba792721e816866ead4982bd507

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
